import { Product, Category } from './types'

// Catégories principales
export const categories: Category[] = [
  {
    id: '1',
    name: 'Protéines',
    slug: 'proteines',
    description: 'Whey, caséine, protéines végétales et isolates',
    icon: '💪',
    productCount: 45,
  },
  {
    id: '2',
    name: 'Acides Aminés',
    slug: 'acides-amines',
    description: 'BCAA, Glutamine, Créatine et plus',
    icon: '⚡',
    productCount: 32,
  },
  {
    id: '3',
    name: 'Minceur',
    slug: 'minceur',
    description: 'Brûleurs de graisse et produits minceur',
    icon: '🔥',
    productCount: 28,
  },
  {
    id: '4',
    name: 'Vitamines & Minéraux',
    slug: 'vitamines-mineraux',
    description: 'Multivitamines, oméga-3 et compléments essentiels',
    icon: '🌿',
    productCount: 38,
  },
  {
    id: '5',
    name: 'Energy & Focus',
    slug: 'energy-focus',
    description: 'Pré-workout, caféine et boosters',
    icon: '⚡',
    productCount: 24,
  },
  {
    id: '6',
    name: 'Barres & Snacks',
    slug: 'barres-snacks',
    description: 'Barres protéinées et snacks sains',
    icon: '🍫',
    productCount: 19,
  },
]

// Produits exemple (à remplacer par une vraie base de données)
export const products: Product[] = [
  {
    id: '1',
    name: 'Whey Protein Isolate',
    slug: 'whey-protein-isolate',
    description: 'Protéine de whey isolate ultra pure, idéale pour la prise de masse musculaire et la récupération.',
    shortDescription: 'Protéine whey isolate 90% de pureté',
    price: 49.99,
    originalPrice: 59.99,
    discount: 17,
    images: ['https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop', 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop'],
    category: 'Protéines',
    brand: 'Nutrigo Pro',
    inStock: true,
    rating: 4.8,
    reviews: 142,
    featured: true,
    bestseller: true,
    tags: ['whey', 'isolate', 'musculation'],
    nutritionalInfo: {
      servingSize: '30g',
      servingsPerContainer: 33,
      calories: 110,
      protein: '27g',
      carbs: '1g',
      fats: '0.5g',
      ingredients: 'Isolat de protéine de lactosérum, arômes naturels, édulcorant (sucralose)',
    },
  },
  {
    id: '2',
    name: 'BCAA 8:1:1',
    slug: 'bcaa-811',
    description: 'Acides aminés branchés en ratio optimal pour maximiser la récupération musculaire.',
    shortDescription: 'BCAA premium ratio 8:1:1',
    price: 29.99,
    images: ['https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&h=400&fit=crop'],
    category: 'Acides Aminés',
    brand: 'Nutrigo Elite',
    inStock: true,
    rating: 4.6,
    reviews: 89,
    bestseller: true,
    tags: ['bcaa', 'récupération', 'endurance'],
  },
  {
    id: '3',
    name: 'Fat Burner Thermogénique',
    slug: 'fat-burner-thermogenique',
    description: 'Brûleur de graisse thermogénique avec L-carnitine et extrait de thé vert.',
    shortDescription: 'Brûleur thermogénique puissant',
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    images: ['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop'],
    category: 'Minceur',
    brand: 'Nutrigo Burn',
    inStock: true,
    rating: 4.5,
    reviews: 67,
    featured: true,
    tags: ['minceur', 'thermogénique', 'définition'],
  },
  {
    id: '4',
    name: 'Créatine Monohydrate',
    slug: 'creatine-monohydrate',
    description: 'Créatine pure micronisée pour améliorer force et performance.',
    shortDescription: 'Créatine pure 100% micronisée',
    price: 24.99,
    images: ['https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400&h=400&fit=crop'],
    category: 'Acides Aminés',
    brand: 'Nutrigo Pro',
    inStock: true,
    rating: 4.9,
    reviews: 203,
    bestseller: true,
    tags: ['créatine', 'force', 'performance'],
  },
]

// Avantages de la boutique
export const shopFeatures = [
  {
    icon: '🚚',
    title: 'Livraison Rapide',
    description: 'Expédition sous 24h',
  },
  {
    icon: '✅',
    title: 'Produits Certifiés',
    description: 'Qualité garantie',
  },
  {
    icon: '💳',
    title: 'Paiement Sécurisé',
    description: 'Transactions 100% protégées',
  },
  {
    icon: '📞',
    title: 'Support Client',
    description: 'À votre écoute 7j/7',
  },
]
